//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Main Screen
export const GET_MAIN_SCREEN_DATA = 'GET_MAIN_SCREEN_DATA';
export const GET_MAIN_SCREEN_DATA_RECIEVED = 'GET_MAIN_SCREEN_DATA_RECIEVED';



